### ISSUE TITLE
Checklist before we invite more folks to write suitcases

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/suitcase-core#61]
## Releases

- [x] Release suitcase-core
- [x] Release suitcase-utils with `[text_fixtures]` "extras" dependency set.
- [x] Finish and (beta-)release suitcase-json-metadata.

## Update cookiecutter

- [x] Update dotfiles.
- [x] Update tests location to `suitcase/X/tests/*`.
- [x] Update default contents of `__init__.py`
- [x] Update default contents of `tests.py` should include usage of `example_data`.
- [x] Refactor requirements-dev.txt to get all the fixture dependencies via `suitcase-utils[text_fixtures]`.
- [x] Decide if it's `serializer._manager` or `serializer.manager`.
